#!/usr/bin/env bash

set -euo pipefail

if [[ $# -gt 0 ]] && [[ $1 == "--clean" ]]; then
    rm -rf "$HOME/.cache/dotfiles/"
    shift 1
fi

source "./header"

sudo -v
clear

setup_debian() {
    if ! [[ -f /etc/apt/sources.list.d/debian.sources ]]; then
        echo "deb http://deb.debian.org/debian ${VERSION_CODENAME} main contrib non-free non-free-firmware" | sudo tee /etc/apt/sources.list
        echo "deb http://deb.debian.org/debian ${VERSION_CODENAME}-updates main contrib non-free non-free-firmware" | sudo tee -a /etc/apt/sources.list
        echo "deb http://security.debian.org/debian-security ${VERSION_CODENAME}-security main contrib non-free non-free-firmware" | sudo tee -a /etc/apt/sources.list

        sudo apt modernize-sources -y

        echo "# DOTFILES" | sudo tee -a /etc/apt/sources.list.d/debian.sources
        echo "# Sources list modified $(date)" | sudo tee -a /etc/apt/sources.list.d/debian.sources
    elif ! grep '^# DOTFILES' /etc/apt/sources.list.d/debian.sources &>/dev/null; then
        sudo rm -rf /etc/apt/sources.list.d/debian.sources

        echo "deb http://deb.debian.org/debian ${VERSION_CODENAME} main contrib non-free non-free-firmware" | sudo tee /etc/apt/sources.list
        echo "deb http://deb.debian.org/debian ${VERSION_CODENAME}-updates main contrib non-free non-free-firmware" | sudo tee -a /etc/apt/sources.list
        echo "deb http://security.debian.org/debian-security ${VERSION_CODENAME}-security main contrib non-free non-free-firmware" | sudo tee -a /etc/apt/sources.list

        sudo apt modernize-sources -y

        echo -e "\n# DOTFILES" | sudo tee -a /etc/apt/sources.list.d/debian.sources
        echo -e "# Sources list modified $(date)" | sudo tee -a /etc/apt/sources.list.d/debian.sources
    fi

    if ! [[ -f /etc/apt/sources.list.d/backports.lists ]] && [[ ! -f /etc/apt/sources.list.d/backports.sources ]]; then
        echo "deb http://deb.debian.org/debian ${VERSION_CODENAME}-backports main contrib non-free non-free-firmware" | sudo tee -a /etc/apt/sources.list.d/backports.list
        sudo apt modernize-sources -y
    fi

    sudo apt-get update -y
    if apt list --upgradable; then
        sudo apt-get upgrade -y
    fi

    if [[ $ISGIT == "$ERROR" ]]; then
        sudo apt-get update -y
        sudo apt install -y git
    fi

    if [[ $ISPYTHON == "$ERROR" ]]; then
        sudo apt-get update -y
        sudo apt install -y python3
    fi

    if [[ $ISPIPX == "$ERROR" ]]; then
        sudo apt-get update -y
        sudo apt install -y pipx
    fi
}

setup_arch() {
    sudo timedatectl set-ntp true

    if ! [[ -f /etc/ld.so.conf.d/local.conf ]]; then
        echo "/usr/local/lib" | sudo tee /etc/ld.so.conf.d/local.conf
        sudo ldconfig
    fi

    if grep -E '^#Color' /etc/pacman.conf &>/dev/null; then
        sudo sed -i '/^#Color/s/^#//' /etc/pacman.conf
    fi

    if grep -E '^#ParallelDownloads[[:space:]]*=[[:space:]]*[0-9]\+' /etc/pacman.conf &>/dev/null; then
        sudo sed -i '/^#ParallelDownloads[[:space:]]*=[[:space:]]*[0-9]\+/s/^#//' /etc/pacman.conf
    fi

    if grep -A 1 '^#[[:space:]]*\[multilib\]' /etc/pacman.conf &>/dev/null; then
        sudo sed -i '/^#[[:space:]]*\[multilib\]/,/^#[[:space:]]*Include = \/etc\/pacman.d\/mirrorlist/s/^#//' /etc/pacman.conf
    fi

    if ! [[ -f /usr/lib/systemd/system/pacman-update.service ]]; then
        sudo cp ./.contents/pacman-update.service /usr/lib/systemd/system/
    fi

    if ! sudo systemctl is-active pacman-update &>/dev/null; then
        sudo systemctl enable pacman-update
    fi

    if ! sudo pacman -Sy; then
        exit 1
    fi
    if sudo pacman -Qu; then
        if ! sudo pacman -Syu --noconfirm; then
            exit 1
        fi
    fi

    if [[ $ISGIT == "$ERROR" ]]; then
        sudo pacman -Sy
        sudo pacman -S --noconfirm git
    fi

    if [[ $ISPYTHON == "$ERROR" ]]; then
        sudo pacman -Sy
        sudo pacman -S --noconfirm python
    fi

    if [[ $ISPIPX == "$ERROR" ]]; then
        sudo pacman -Sy
        sudo pacman -S --noconfirm python-pipx
    fi
}

# echo -e "* Preparing OS"
case "${OS}" in
debian)
    if ! setup_debian 2>$LOGFILE; then
        clear
        echo -e "$ERROR, Failed to prepare OS check log $LOGFILE"
        exit 1
    fi
    ;;
arch)
    if ! setup_arch 2>$LOGFILE; then
        clear
        echo -e "$ERROR, Failed to prepare OS check log $LOGFILE"
        exit 1
    fi
    ;;
*)
    echo -e "$ERROR, ${OS}, is not supported"
    exit 1
    ;;
esac

if [[ $ISANSIBLE == "$ERROR" ]]; then
    echo -e "* Installing ansible"
    if ! pipx install --include-deps ansible==$ANSIBLE_VERSION 2>"$LOGFILE"; then
        clear
        echo -e "$ERROR, Failed to install ansible $ANSIBLE_VERSION, see log $LOGFILE"
        exit 1
    fi
fi

if [[ -n $OS ]]; then
    clear
    if ! ansible-playbook local.yaml "${ANSIBLE_ARGS[@]}" "${@}"; then
        exit 1
    fi
fi
