- name: Downloading go for Linux
  when: ansible_facts.system == 'Linux'
  ansible.builtin.get_url:
      url: 'https://go.dev/dl/go{{ GO_VERSION }}.linux-amd64.tar.gz'
      dest: '{{ DOTFILES_CACHE_DIR }}/go.tar.gz'
  tags: go

- name: Creating go installation path
  ansible.builtin.file:
      dest: '{{ HOME_DIR }}/.go/version/go{{ GO_VERSION }}'
      state: directory
  tags: go

- name: Extracting go for Linux
  ansible.builtin.unarchive:
      src: '{{ DOTFILES_CACHE_DIR }}/go.tar.gz'
      dest: '{{ HOME_DIR }}/.go/version/go{{ GO_VERSION }}'
      extra_opts: [--strip-components=1]
  tags: go

- name: Configuring go environment
  ansible.builtin.blockinfile:
      path: '{{ HOME_DIR }}/.zshrc'
      prepend_newline: true
      marker: '# {mark} go'
      block: |
          export GOPATH="$HOME/.go"
          export PATH="$PATH:$GOPATH/version/go{{ GO_VERSION }}/bin"
          export PATH="$PATH:$GOPATH/bin"
  loop: [.zshrc, .bashrc]
  tags: go
