- name: Installing nodejs
  ansible.builtin.shell: |
      NODE_DIR="$HOME/.node"

      curl -fsSL https://fnm.vercel.app/install |
          bash -s -- --skip-shell --install-dir $NODE_DIR/manager/bin

      export FNM_MULTISHELL_PATH="$NODE_DIR"
      export FNM_DIR="$NODE_DIR/manager"
      export PATH="$NODE_DIR/manager/bin:$PATH"

      fnm install --lts
  tags: nodejs

- name: Configuring nodejs environment
  ansible.builtin.blockinfile:
      path: '{{ HOME_DIR }}/.zshrc'
      prepend_newline: true
      marker: '# {mark} nodejs'
      block: |
          export PATH="$HOME/.node/manager/bin:$PATH"
          export NPM_CONFIG_CACHE=$HOME/.node
          export NPM_CONFIG_PREFIX=$HOME/.node
          if command -v fnm &>/dev/null; then
             eval "$(fnm env --shell zsh)"
          fi
          export FNM_DIR=$HOME/.node/manager
  loop: [.zshrc, .bashrc]
  tags: nodejs
