- name: Installing nodejs
  ansible.builtin.shell: |
      export NVM_DIR="$HOME/.node"

      mkdir -p $NVM_DIR
      curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash

      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

      nvm install --lts
      npm config set cache=$NVM_DIR/.cache
  tags: nodejs

- name: Configuring nodejs environment
  ansible.builtin.blockinfile:
      path: '{{ HOME_DIR }}/.zshrc'
      prepend_newline: true
      marker: '# {mark} nodejs'
      block: |
          export NVM_DIR="$HOME/.node"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
  loop: [.zshrc, .bashrc]
  tags: nodejs
